### ISSUE TITLE
Extension keeps re-downloading the latest version - every launch

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarity-lsp#1]

**Comment by agraebe** [comment]
good first issue

**Comment by pxydn** [comment]
is this the same issue? always redownloads latest version but then gets stuck on 100%

---
<img alt="Screenshot 2021-04-30 at 09 40 29" src="https://user-images.githubusercontent.com/67651251/116670836-1bb67e80-a998-11eb-96a0-536c56fcbd63.png">

**Comment by michaelgold** [comment]
> is this the same issue? always redownloads latest version but then gets stuck on 100%

The same thing happened on my machine. I was able to work around this issue by Installing clarity-lsp from source.

from the readme:
```
git clone https://github.com/lgalabru/clarity-lsp.git
cd clarity-lsp
cargo xtask install
```

**Comment by lgalabru** [comment]
Should be addressed with latest.
