### ISSUE TITLE
Wrongly shows error for read-only contract calls

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarity-lsp#11]
In VS Code, an error is shown for the following contract
```
(define-read-only (flip-coin-delegate)
  (contract-call? .flip-coin flip-coin)
)
```

`flip-coin.flip-coin` is a read-only function

![Screenshot from 2020-05-27 01-22-24](https://user-images.githubusercontent.com/1449049/82990799-06550980-9ffd-11ea-99e3-4ddefd843fba.png)

Related issue: https://github.com/blockstack/stacks-blockchain/issues/1630

**Comment by lgalabru** [comment]
Addressed with latest!
