### ISSUE TITLE
Plugin throws error "Use of unresolved contract"

### ISSUE THREAD

**Issue by philipdesmedt** [hirosystems/clarity-lsp#20]
When doing a `contract-call?` method call, the VSCode plugin throws an error. Something like this:

```
use of unresolved contract 'S1G2081040G2081040G2081040G208105NK8PE5.oracle'
```

The error doesn't resolve itself by adding a smart contract address or not. I saw in the documentation this was a missing feature still.

**Comment by lgalabru** [comment]
Thanks @philipdesmedt, will fix!

**Comment by lgalabru** [comment]
Addressed with latest!

**Comment by obycode** [comment]
@unclemantis Please provide a reproducer. Thanks!

**Comment by unclemantis** [comment]
> @unclemantis Please provide a reproducer. Thanks!

Not sure what I did but stuff is working BEAUTIFUL.  All node and packages etc are up to date.  That might have been it.  Freaking months of breaking change hell until one day everyone agrees to work together.  LOL
