### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarity-lsp#22]
After switching to using `clarinet lsp`, there is a good bit of unused code in this repo that needs to be cleaned up.

**Comment by hugoclrd** [comment]
@obycode 
I have a few questions about this one;
- In the end we can remove all the rust related code on the repos (`src/`, `xtask/` and some other files)?
- Should we also restructure the `./editors/code/` directory into just `./code`?

Let me know what you think

**Comment by obycode** [comment]
Yes, that sounds right to me! It seems that we've settled on only supporting VS Code, so maybe we could simplify that even further. Thoughts @lgalabru?
