### ISSUE TITLE
Rename clarity-lsp to clarinet-vscode and update to Hiro logo

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarity-lsp#25]
The search term for "clarity" is overloaded in the VSCode Marketplace. There are at least 3 extensions and things like themes that show up before our extension. 

To avoid developer confusion and with the addition of UI components building on top of Clarinet, we could rename the extension to "Clarinet for VSCode" (or just "Clarinet"). 

Logo (all white and transparent, difficult to see on GH):
![hiro-icon-white](https://user-images.githubusercontent.com/1671228/122833793-6a024280-d2a2-11eb-8db8-05224844e168.png)

**Comment by MarvinJanssen** [comment]
Even though there are a few plugins using "Clarity" in the name, do you think taking the name out altogether is the best way to go? It is a *Clarity* language plugin after all. It would definitely be the first thing most developers enter into the marketplace search bar. (Also, you can search by file extension as well.)

**Comment by agraebe** [comment]
that's a good point. I'm not sure how many search directly for an extension (wihtout being pointed to it from within docs or so).

I just tried searching for "stacks" and it shows all our extensions, so I assume we could add "clarity" and "stacks" to the description to make sure it is showing up?

**Comment by LNow** [comment]
@lgalabru added to this repository syntax highlighting files I created, so I'll remove my extension from the marketpace today or tomorrow. There is no need to keep 2 extensions with exactly the same highlighting.

**Comment by MarvinJanssen** [comment]
@agraebe you're right. If we add the right tags we can name it anything we like.

I think my vote for a plugin name would still be something like "Clarity for Visual Studio Code" 😁

**Comment by agraebe** [comment]
Makes sense to me! Especially once we remove other extensions, it'll become easier to find the right one.

@lgalabru - any thoughts?

**Comment by lgalabru** [comment]
Changing clarity-lsp is an invasive change that would break many things, but name and logo were updated.
