### ISSUE TITLE
Extension doesn't work with WSL

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarity-lsp#27]
When I tried to add this extension to my WSL it wasn't able to start LSP client, failed to deliver proper syntax highlighting and messed up with brackets highlighting.

Unfortunately I can't provide any meaningful logs as extendible doesn't produce any.

**Comment by lgalabru** [comment]
Hey @LNow! Do you mind trying again with the latest release from the Marketplace (0.5.3)? Thanks!

**Comment by LNow** [comment]
@lgalabru now it works correctly.
Thank you for fixing it!
