### ISSUE TITLE
Release M1 mac binaries

### ISSUE THREAD

**Issue by pgray-hiro** [hirosystems/clarity-lsp#34]
When using the extension on Apple silicon, the extension gives a notification

> Unfortunately we don't ship binaries for your platform yet. You need to manually clone clarity-lsp repository and run `cargo xtask install --server` to build the language server from source.

Please support the arm64 platform and build binaries for it.

**Comment by SyAsteria** [comment]
I'm also having this error, would like arm64 binaries. If it's easy enough I'll submit a PR to try solve this

**Comment by pors** [comment]
I tried to compile it myself like:

```
git clone https://github.com/hirosystems/clarity-lsp.git
cd clarity-lsp
cargo xtask install
```

Resulting in: `Extension 'clarity-lsp.vsix' was successfully installed.`.

What am I supposed to do next? VSCode doesn't seem to find it by itself.

**Comment by pors** [comment]
> I tried to compile it myself like:
> 
> ```
> git clone https://github.com/hirosystems/clarity-lsp.git
> cd clarity-lsp
> cargo xtask install
> ```
> 
> Resulting in: `Extension 'clarity-lsp.vsix' was successfully installed.`.
> 
> What am I supposed to do next? VSCode doesn't seem to find it by itself.

I figured it out: in VSCode there is an option "Install from VSIX"

**Comment by dcsan** [comment]
for anyone else looking for this it ends up here after building:

![image](https://user-images.githubusercontent.com/514002/144780094-9a4a76c9-61d6-4fcc-b83c-229ab8ca31e8.png)

**Comment by dcsan** [comment]
but after compiling from source now the plugin gives me an upgrade warning..

![image](https://user-images.githubusercontent.com/514002/144780169-8a743dc0-9d3b-4edf-96ff-abd0681724c4.png)

![image](https://user-images.githubusercontent.com/514002/144780214-1cc42dbe-6c93-45b0-94a5-b6053740b3dd.png)

and then back to this. so maybe it's best to compile source from a different branch in the repo?

![image](https://user-images.githubusercontent.com/514002/144780236-fac795a2-49cb-47ff-9c57-78d6d7196fba.png)

**Comment by shareef-dweikat** [comment]
I get `zsh: command not found: cargo` after running `cargo xtask install --server`

**Comment by lgalabru** [comment]
Issue addressed with the latest version of the extension (v0.6.0), simply make sure that you're using the latest version of Clarinet (v0.22.0).

**Comment by pors** [comment]
Awesome!!!!!! Thanks so much!
