### ISSUE TITLE
[BUG] clarity-lsp is not installed

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarity-lsp#35]
Developers seem to see an error upon installation: `clarity-lsp is not installed`

**Comment by fluidvoice** [comment]
yes I got this error with VS Code 1.58 on Manjaro - the version in the main/core Arch repository:
https://aur.archlinux.org/packages/code-transparent 
It looks like **clarity-lsp** is not being installed correctly or it's not found in the path.
I installed via `ctrl-p "ext install HiroSystems.clarity-lsp"`

VSCode Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.1.0
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.143-1-MANJARO

**Comment by fluidvoice** [comment]
I uninstalled the v1.58.0 version of VS Code.
deleted `~/.config/Code - OSS/` and `/home/brad/.vscode/` directories
Then installed v1.60.1 of VSCode from the AUR (Arch User Repository) for Ach/Manjaro
https://aur.archlinux.org/packages/visual-studio-code-bin
Then installed the Clarity plugin again **and it worked:** `ctrl-p "ext install HiroSystems.clarity-lsp"`


Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:06:57.931Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.143-1-MANJARO

**Comment by lgalabru** [comment]
Issue addressed with the latest version of the extension (v0.6.0), simply make sure that you're using the latest version of Clarinet (v0.22.0).
