### ISSUE TITLE
"Failed to lex input remainder" upon save of all .clar

### ISSUE THREAD

**Issue by cryptocracy** [hirosystems/clarity-lsp#41]
I decided to try to use the VSCode Extension.
The syntax highlighting seems to work fine, however ALL(if created by VScode) clarity contracts yield Errors Detected upon saving.

All of them indicate: 
"Failed to lex input remainder"

I'm running the latest version of VSCode and Extension.

I first noticed this as I was simply trying to review the `hey.clar` and `hey-token.clar` per [https://github.com/blockstack/heystack/tree/main/contracts](https://github.com/blockstack/heystack/tree/main/contracts)

After having no luck I tested other src per contracts found on chain and they even yield the same error upon local save.

OS: Win10 

-----

**My Testing:**
When I use VSCode to create the .clar files, all files upon save throw Error detected in VSCode error log say "Failed to lex input remainder".

When I use my Dapparatus and write new .clar files with ASCII encoding, I get more specific errors reported back by VSCode error log when subsequently evaluating them and saving them again per VSCode.

When I use my Dapparatus to evaluate (per embedded clarity-cli) the various files I get back:
1) files created by Vscode as .clar files all return `Unexpected end of JSON input`
2) files created by Dapparatus as .clar files all return more robust errors with analysis. 

Note: I use a exe node to pass `check filename.clar`  into the `clarity-cli.exe` run time and report back errors.

I think this relates to:  #42

**Comment by cryptocracy** [comment]
Hmmm this might not be ALL files after all.

**Comment by lgalabru** [comment]
For windows users, you should make sure that your VSCode is configured for using LF, instead of CRLF.
