### ISSUE TITLE
Plugin throws error "Use of unresolved contract" 

### ISSUE THREAD

**Issue by cryptocracy** [hirosystems/clarity-lsp#42]
So it looks like this was addressed once before per issue #20 

I'm attempting to debug two clarity contracts (that are basically just clones of the `hey.clar` and `hey-token.clar`.

My copy is called `luv.clar` and its yielding: 

Error:
```
use of unresolved contract 'SP1T33SDB0Y1GE9WBN0X3G6MZ81XQG2XVNBHMRH1V.luv-token'
```

Clarity snippet:
```
(define-private (get-balance (recipient principal))
  (contract-call? 'SP1T33SDB0Y1GE9WBN0X3G6MZ81XQG2XVNBHMRH1V.luv-token get-balance recipient)
)
```

OS: Win10

-----

**My Testing:**
When I use VSCode to create the .clar files, all files upon save throw Error detected in VSCode error log say "Failed to lex input remainder".

When I use my Dapparatus and write new .clar files with ASCII encoding, I get more specific errors reported back by VSCode error log when subsequently evaluating them and saving them again per VSCode.

When I use my Dapparatus to evaluate (per embedded clarity-cli) the various files I get back:
1) files created by Vscode as .clar files all return `Unexpected end of JSON input`
2) files created by Dapparatus as .clar files all return more robust errors with analysis. 

Note: I use a exe node to pass `check filename.clar`  into the `clarity-cli.exe` run time and report back errors.

I think this relates to: #41

**Comment by agraebe** [comment]
The error `use of unresolved contract` came up in developer research as well @lgalabru

**Comment by lgalabru** [comment]
Issue addressed with the latest version of the extension (v0.6.0), simply make sure that you're using the latest version of Clarinet (v0.22.0).
