### ISSUE TITLE
[BUG] clarity-lsp is not installed

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarity-lsp#44]
Developers seem to see an error upon installation: `clarity-lsp is not installed`

**Comment by fluidvoice** [comment]
I uninstalled that version, 
deleted `~/.config/Code - OSS/` and `/home/brad/.vscode/` directories
Then installed v1.60.1 from the AUR (Arch User Repository) for Ach/Manjaro
Then installed again and it worked OK.


Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:06:57.931Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.143-1-MANJARO

**Comment by lgalabru** [comment]
Issue addressed with the latest version of the extension (v0.6.0), simply make sure that you're using the latest version of Clarinet (v0.22.0).
