### ISSUE TITLE
[BUG] Highlighting stopping or incorrect

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarity-lsp#45]
Developers remarked that the syntax highlighting stops working somes. Othertimes, invalid errors seem to be shown. 

Requires more troubleshooting to better understand the issue.

**Comment by lgalabru** [comment]
We need to address this issue. Meanwhile, per @obycode, enabling and disabling the extension can be used as a workaround.

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/clarity-repl/pull/67 and upcoming version of clarinet (> v0.22.0)
