### ISSUE TITLE
Wrongly shows error for read-only contract calls

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarity-lsp#50]
In VS Code, an error is shown for the following contract
```
(define-read-only (flip-coin-delegate)
  (contract-call? .flip-coin flip-coin)
)
```

`flip-coin.flip-coin` is a read-only function

![Screenshot from 2020-05-27 01-22-24](https://user-images.githubusercontent.com/1449049/82990799-06550980-9ffd-11ea-99e3-4ddefd843fba.png)

Related issue: https://github.com/blockstack/stacks-blockchain/issues/1630

**Comment by lgalabru** [comment]
Thank you for this bug report @friedger. Support for `contract-call?` is definitely at the very top of my list - https://github.com/lgalabru/clarity-lsp#additional-desired-features-not-exhaustive-not-prioritized
I need to think more about ways to do so.

**Comment by lgalabru** [comment]
Addressed with latest!
