### ISSUE TITLE
[vscode extension] - use of unresolved contract 

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarity-lsp#51]
I understand from the readme that the extension should be abl to resolve call-contract on local contract, but when trying to do so, VSCode says there an error `use of unresolved contract 'S1G...K8PE5.sub-contract`. Although my code works just fine.

Same when trying to do `(impl-trait .sip009-nft-trait.sip009-nft-trait)` with a local trait, I get `use of undeclared trait <sip009-nft-trait>`.

Is there any workaround or way to make it work?
Thanks

**Comment by lgalabru** [comment]
Hey @hugocaillard! That's odd, and could be a bug. In your `Clarinet.toml` manifest, are you correctly listing this trait in the `depends_on` field of the contract referencing it?

**Comment by hugocaillard** [comment]
Hello @lgalabru , thanks for coming back at me. Yes the Clarinet.toml is correct. `clarinet console`, `clarinet check` etc throw no errors at my projects, but VS Code does.
Also, multiple people on the Discord encountered the same issue, I never knew who to ping about that but I just realised that there was a `clarinet` channel (thanks to your message about 0.19 actually)

**Comment by hugocaillard** [comment]
@lgalabru Btw I was able to fix the issue by manually downloading [claruty-lsp](https://github.com/hirosystems/clarity-lsp) and adding ` "clarity-lsp.serverPath": "/usr/local/bin/clarity-lsp"` to my VSCode config.
It works but not out of the box.
Also, now everytime I open a clarity project in VSCode, I have another VSCode icon bouncing in my dock. And if I force quit it, the clarity extension crashes.

Not sure how all of this is related. Tell me if you want me to open another issue. We can also talk about it on Discord

(Using MacOS BigSur on an Intel MBP)

**Comment by csgui** [comment]
Hey @hugocaillard !

I've pointed the `clarity-lsp.serverPath` to a local build of the `clarity-lsp` but the error still persists. 

![image](https://user-images.githubusercontent.com/13015/148109685-8699ef94-d031-4b09-a00a-947eff6c0427.png)

I was wondering from where that address `S1G2081040G2081040G2081040G208105NK8PE5` comes from? 🤔 

@lgalabru any hint?

Cheers!

**Comment by lgalabru** [comment]
Hey @hugocaillard, @csgui!
Apologies for the latency on this issue - finally coming to an end with https://github.com/hirosystems/clarity-lsp/pull/54.

**Comment by lgalabru** [comment]
Issue addressed with the latest version of the extension (v0.6.0), simply make sure that you're using the latest version of Clarinet (v0.22.0).

**Comment by hugocaillard** [comment]
@lgalabru Just updated everything and it works like a charm. Thanks a lot

**Comment by lgalabru** [comment]
Great, thanks for confirming!
