### ISSUE TITLE
Wrong syntax color for function args

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarity-lsp#63]
When a function arg has a "complex" type (ie: `(list 10 uint)` or `(string-utf8 10)`), it breaks the following args colors.
<img width="475" alt="Screenshot 2022-01-20 at 17 40 36" src="https://user-images.githubusercontent.com/911307/150384908-de63e575-ba8b-49ac-b2c6-451e999350c5.png">

I tried to tweak the regexps but didn't find a way to reliably fix it so far.
Maybe I'll try to come back on it later but I might need some guidance

**Comment by LNow** [comment]
I'll take care of it :wink: 

New version (almost finished) will produce something like this:
![image](https://user-images.githubusercontent.com/829210/153290844-ecf7276d-d619-4c4b-a179-ccb42f655032.png)

**Comment by obycode** [comment]
Cool thanks! Looking forward to your PR.

**Comment by hugocaillard** [comment]
Seems to be fixed 👍  Thx
