### ISSUE TITLE
Regression on traits syntax highlighting

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarity-lsp#80]
Look like syntax highlighting is broken on traits definition. Is especially obvious for comment. See screenshote.

<img width="218" alt="Screenshot 2022-03-01 at 15 35 31" src="https://user-images.githubusercontent.com/911307/156190862-ecb7d8b9-e129-46b2-8ef3-b777153c9d0f.png">

**Comment by hugocaillard** [comment]
@LNow I have the same issue on comments in tuple inside "define-map" like so. 
```
;; right color
(define-map hello uint {
  key: uint ;; wrong color
})
```
<img width="150" alt="Screenshot 2022-03-03 at 20 06 03" src="https://user-images.githubusercontent.com/911307/156635046-35fb0824-34e1-4d14-a6f6-9722be62bf96.png">

Wanted to let you know before the PR is merged

**Comment by LNow** [comment]
@hugocaillard good catch!!
Submitted additional commit. It also fixes few other problems with comments in data types.

After fix:
![image](https://user-images.githubusercontent.com/829210/156639977-e158a6cf-3559-4dde-bbd9-564f8b806c03.png)
