### ISSUE TITLE
[BUG] POX contract is treated as unresolved

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarity-lsp#85]
When we try to use POX contract in our contract LSP displays an error that `SP000000000000000000002Q6VF78.pox` is unresolved, despite the fact that it is accessible in clarinet.

Sample contract:
```clarity
(print
  (contract-call? 'SP000000000000000000002Q6VF78.pox stack-stx u2600000000 {hashbytes: 0xf632e6f9d29bfb07bc8948ca6e0dd09358f003ac, version: 0x00} u726703 u1)
)
```

Error:
![image](https://user-images.githubusercontent.com/829210/157675333-8ab6665d-c6ae-48bf-97ed-33a98ae65d55.png)

**Comment by obycode** [comment]
This should be fixed by hirosystems/clarinet#333.
